//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicExpresso.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DynamicExpresso.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AmbiguousIndexerInvocation {
            get {
                return ResourceManager.GetString("AmbiguousIndexerInvocation", resourceCulture);
            }
        }
        
        internal static string AmbiguousMethodInvocation {
            get {
                return ResourceManager.GetString("AmbiguousMethodInvocation", resourceCulture);
            }
        }
        
        internal static string ArgsIncompatibleWithDelegate {
            get {
                return ResourceManager.GetString("ArgsIncompatibleWithDelegate", resourceCulture);
            }
        }
        
        internal static string ArgsIncompatibleWithLambda {
            get {
                return ResourceManager.GetString("ArgsIncompatibleWithLambda", resourceCulture);
            }
        }
        
        internal static string BothTypesConvertToOther {
            get {
                return ResourceManager.GetString("BothTypesConvertToOther", resourceCulture);
            }
        }
        
        internal static string CannotConvertValue {
            get {
                return ResourceManager.GetString("CannotConvertValue", resourceCulture);
            }
        }
        
        internal static string CloseBracketOrCommaExpected {
            get {
                return ResourceManager.GetString("CloseBracketOrCommaExpected", resourceCulture);
            }
        }
        
        internal static string CloseParenOrCommaExpected {
            get {
                return ResourceManager.GetString("CloseParenOrCommaExpected", resourceCulture);
            }
        }
        
        internal static string CloseParenOrOperatorExpected {
            get {
                return ResourceManager.GetString("CloseParenOrOperatorExpected", resourceCulture);
            }
        }
        
        internal static string ColonExpected {
            get {
                return ResourceManager.GetString("ColonExpected", resourceCulture);
            }
        }
        
        internal static string DigitExpected {
            get {
                return ResourceManager.GetString("DigitExpected", resourceCulture);
            }
        }
        
        internal static string DotOrOpenParenExpected {
            get {
                return ResourceManager.GetString("DotOrOpenParenExpected", resourceCulture);
            }
        }
        
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        internal static string ExpressionMustBeWritable {
            get {
                return ResourceManager.GetString("ExpressionMustBeWritable", resourceCulture);
            }
        }
        
        internal static string FirstExprMustBeBool {
            get {
                return ResourceManager.GetString("FirstExprMustBeBool", resourceCulture);
            }
        }
        
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        internal static string IncompatibleOperand {
            get {
                return ResourceManager.GetString("IncompatibleOperand", resourceCulture);
            }
        }
        
        internal static string IncompatibleOperands {
            get {
                return ResourceManager.GetString("IncompatibleOperands", resourceCulture);
            }
        }
        
        internal static string IncorrectNumberOfIndexes {
            get {
                return ResourceManager.GetString("IncorrectNumberOfIndexes", resourceCulture);
            }
        }
        
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        internal static string InvalidCharacterLiteral {
            get {
                return ResourceManager.GetString("InvalidCharacterLiteral", resourceCulture);
            }
        }
        
        internal static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        internal static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        internal static string InvalidIntegerLiteral {
            get {
                return ResourceManager.GetString("InvalidIntegerLiteral", resourceCulture);
            }
        }
        
        internal static string InvalidMethodCall {
            get {
                return ResourceManager.GetString("InvalidMethodCall", resourceCulture);
            }
        }
        
        internal static string InvalidRealLiteral {
            get {
                return ResourceManager.GetString("InvalidRealLiteral", resourceCulture);
            }
        }
        
        internal static string NeitherTypeConvertsToOther {
            get {
                return ResourceManager.GetString("NeitherTypeConvertsToOther", resourceCulture);
            }
        }
        
        internal static string NoApplicableConstructor {
            get {
                return ResourceManager.GetString("NoApplicableConstructor", resourceCulture);
            }
        }
        
        internal static string NoApplicableIndexer {
            get {
                return ResourceManager.GetString("NoApplicableIndexer", resourceCulture);
            }
        }
        
        internal static string OpenParenExpected {
            get {
                return ResourceManager.GetString("OpenParenExpected", resourceCulture);
            }
        }
        
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        internal static string TypeHasNoNullableForm {
            get {
                return ResourceManager.GetString("TypeHasNoNullableForm", resourceCulture);
            }
        }
        
        internal static string TypeIdentifierExpected {
            get {
                return ResourceManager.GetString("TypeIdentifierExpected", resourceCulture);
            }
        }
        
        internal static string TypeofRequiresAType {
            get {
                return ResourceManager.GetString("TypeofRequiresAType", resourceCulture);
            }
        }
        
        internal static string TypeofRequiresOneArg {
            get {
                return ResourceManager.GetString("TypeofRequiresOneArg", resourceCulture);
            }
        }
        
        internal static string UnknownPropertyOrField {
            get {
                return ResourceManager.GetString("UnknownPropertyOrField", resourceCulture);
            }
        }
        
        internal static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        internal static string AmbiguousBinaryOperatorInvocation {
            get {
                return ResourceManager.GetString("AmbiguousBinaryOperatorInvocation", resourceCulture);
            }
        }
        
        internal static string AmbiguousUnaryOperatorInvocation {
            get {
                return ResourceManager.GetString("AmbiguousUnaryOperatorInvocation", resourceCulture);
            }
        }
        
        internal static string AmbiguousDelegateInvocation {
            get {
                return ResourceManager.GetString("AmbiguousDelegateInvocation", resourceCulture);
            }
        }
        
        internal static string CloseCurlyBracketExpected {
            get {
                return ResourceManager.GetString("CloseCurlyBracketExpected", resourceCulture);
            }
        }
        
        internal static string OpenCurlyBracketExpected {
            get {
                return ResourceManager.GetString("OpenCurlyBracketExpected", resourceCulture);
            }
        }
        
        internal static string EqualExpected {
            get {
                return ResourceManager.GetString("EqualExpected", resourceCulture);
            }
        }
        
        internal static string CloseTypeArgumentListExpected {
            get {
                return ResourceManager.GetString("CloseTypeArgumentListExpected", resourceCulture);
            }
        }
        
        internal static string MethodTypeParametersCantBeInferred {
            get {
                return ResourceManager.GetString("MethodTypeParametersCantBeInferred", resourceCulture);
            }
        }
        
        internal static string ParamsArrayTypeNotAnArray {
            get {
                return ResourceManager.GetString("ParamsArrayTypeNotAnArray", resourceCulture);
            }
        }
        
        internal static string AmbiguousConstructorInvocation {
            get {
                return ResourceManager.GetString("AmbiguousConstructorInvocation", resourceCulture);
            }
        }
        
        internal static string UnsupportedMultidimensionalArrays {
            get {
                return ResourceManager.GetString("UnsupportedMultidimensionalArrays", resourceCulture);
            }
        }
        
        internal static string InvalidInitializerMemberDeclarator {
            get {
                return ResourceManager.GetString("InvalidInitializerMemberDeclarator", resourceCulture);
            }
        }
        
        internal static string CollectionInitializationNotSupported {
            get {
                return ResourceManager.GetString("CollectionInitializationNotSupported", resourceCulture);
            }
        }
        
        internal static string UnableToFindAppropriateAddMethod {
            get {
                return ResourceManager.GetString("UnableToFindAppropriateAddMethod", resourceCulture);
            }
        }
        
        internal static string ReservedWord {
            get {
                return ResourceManager.GetString("ReservedWord", resourceCulture);
            }
        }
        
        internal static string ArgumentCountMismatch {
            get {
                return ResourceManager.GetString("ArgumentCountMismatch", resourceCulture);
            }
        }
        
        internal static string GenericTypeReference {
            get {
                return ResourceManager.GetString("GenericTypeReference", resourceCulture);
            }
        }
        
        internal static string AssignmentOperatorNotAllowed {
            get {
                return ResourceManager.GetString("AssignmentOperatorNotAllowed", resourceCulture);
            }
        }
        
        internal static string DuplicateParameter {
            get {
                return ResourceManager.GetString("DuplicateParameter", resourceCulture);
            }
        }
        
        internal static string InvalidMethodCall2 {
            get {
                return ResourceManager.GetString("InvalidMethodCall2", resourceCulture);
            }
        }
        
        internal static string ReflectionNotAllowed {
            get {
                return ResourceManager.GetString("ReflectionNotAllowed", resourceCulture);
            }
        }
        
        internal static string UnknownIdentifier {
            get {
                return ResourceManager.GetString("UnknownIdentifier", resourceCulture);
            }
        }
        
        internal static string DuplicateLocalParameterDeclaration {
            get {
                return ResourceManager.GetString("DuplicateLocalParameterDeclaration", resourceCulture);
            }
        }
        
        internal static string MultipleLambdaParametersWithoutBrace {
            get {
                return ResourceManager.GetString("MultipleLambdaParametersWithoutBrace", resourceCulture);
            }
        }
        
        internal static string GenericArgumentCountMismatch {
            get {
                return ResourceManager.GetString("GenericArgumentCountMismatch", resourceCulture);
            }
        }
        
        internal static string NextTokenAtEnd {
            get {
                return ResourceManager.GetString("NextTokenAtEnd", resourceCulture);
            }
        }
    }
}
